/**
 * Comprehensive Directory of Licensed Nigerian Banks & Financial Institutions.
 *
 * CBN-Licensed Directory covering:
 *   - All 26 Licensed Commercial Banks
 *   - Leading Digital Neobanks & Top FinTech MFBs
 *   - Non-Interest / Islamic Banks (Jaiz, TAJ, Lotus, Alternative)
 *   - Merchant Banks (Coronation, FBNQuest, Rand, Greenwich, FSDH)
 *   - National & State Microfinance Banks (LAPO, Accion, Baobab, AB MFB, etc.)
 *   - Custom / Other Bank entry support
 */

export interface BankMeta {
  key: string;
  name: string;
  short: string;
  category: 'commercial' | 'digital' | 'microfinance' | 'other';
  defaultScheme: 'mastercard' | 'visa' | 'verve';
  primaryColor: string;
  gradient: string;
  isPopular?: boolean;
}

export const ALL_NIGERIAN_BANKS: BankMeta[] = [
  // ── Commercial Banks (All 26 Licensed Commercial Banks) ──
  {
    key: 'gtbank',
    name: 'Guaranty Trust Bank (GTBank)',
    short: 'GTBank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#ff5a00',
    gradient: 'linear-gradient(135deg, #111827 0%, #1f2937 60%, #111827 100%)',
    isPopular: true,
  },
  {
    key: 'zenith',
    name: 'Zenith Bank Plc',
    short: 'Zenith Bank',
    category: 'commercial',
    defaultScheme: 'visa',
    primaryColor: '#e11d48',
    gradient: 'linear-gradient(135deg, #0e172a 0%, #1e293b 50%, #0f172a 100%)',
    isPopular: true,
  },
  {
    key: 'access',
    name: 'Access Bank Plc',
    short: 'Access Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#f97316',
    gradient: 'linear-gradient(135deg, #02182b 0%, #0b2545 60%, #061a40 100%)',
    isPopular: true,
  },
  {
    key: 'firstbank',
    name: 'First Bank of Nigeria',
    short: 'FirstBank',
    category: 'commercial',
    defaultScheme: 'visa',
    primaryColor: '#041e42',
    gradient: 'linear-gradient(135deg, #041e42 0%, #0c2340 55%, #001e44 100%)',
    isPopular: true,
  },
  {
    key: 'uba',
    name: 'United Bank for Africa (UBA)',
    short: 'UBA',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#c8102e',
    gradient: 'linear-gradient(135deg, #171717 0%, #262626 60%, #171717 100%)',
    isPopular: true,
  },
  {
    key: 'stanbic',
    name: 'Stanbic IBTC Bank',
    short: 'Stanbic IBTC',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#0033aa',
    gradient: 'linear-gradient(135deg, #001e62 0%, #0033aa 60%, #001845 100%)',
    isPopular: true,
  },
  {
    key: 'fidelity',
    name: 'Fidelity Bank Plc',
    short: 'Fidelity Bank',
    category: 'commercial',
    defaultScheme: 'visa',
    primaryColor: '#004b87',
    gradient: 'linear-gradient(135deg, #002d62 0%, #004b87 60%, #006644 100%)',
  },
  {
    key: 'fcmb',
    name: 'First City Monument Bank (FCMB)',
    short: 'FCMB',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#5c068c',
    gradient: 'linear-gradient(135deg, #2e0854 0%, #5c068c 60%, #3b0259 100%)',
  },
  {
    key: 'wema',
    name: 'Wema Bank (ALAT)',
    short: 'Wema / ALAT',
    category: 'commercial',
    defaultScheme: 'verve',
    primaryColor: '#93186c',
    gradient: 'linear-gradient(135deg, #4a044e 0%, #93186c 60%, #701a75 100%)',
    isPopular: true,
  },
  {
    key: 'sterling',
    name: 'Sterling Bank Plc',
    short: 'Sterling Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#c41230',
    gradient: 'linear-gradient(135deg, #1e293b 0%, #334155 60%, #c41230 100%)',
  },
  {
    key: 'union',
    name: 'Union Bank of Nigeria',
    short: 'Union Bank',
    category: 'commercial',
    defaultScheme: 'verve',
    primaryColor: '#0099ff',
    gradient: 'linear-gradient(135deg, #0369a1 0%, #0284c7 60%, #0c4a6e 100%)',
  },
  {
    key: 'polaris',
    name: 'Polaris Bank',
    short: 'Polaris Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#6a1b9a',
    gradient: 'linear-gradient(135deg, #2e1065 0%, #581c87 60%, #3b0764 100%)',
  },
  {
    key: 'ecobank',
    name: 'Ecobank Nigeria',
    short: 'Ecobank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#005b94',
    gradient: 'linear-gradient(135deg, #075985 0%, #0369a1 60%, #0c4a6e 100%)',
  },
  {
    key: 'keystone',
    name: 'Keystone Bank',
    short: 'Keystone Bank',
    category: 'commercial',
    defaultScheme: 'visa',
    primaryColor: '#002f6c',
    gradient: 'linear-gradient(135deg, #0c2340 0%, #0f3260 60%, #001e44 100%)',
  },
  {
    key: 'providus',
    name: 'Providus Bank',
    short: 'Providus Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#d97706',
    gradient: 'linear-gradient(135deg, #18181b 0%, #27272a 60%, #78350f 100%)',
  },
  {
    key: 'standardchartered',
    name: 'Standard Chartered Bank',
    short: 'StanChart',
    category: 'commercial',
    defaultScheme: 'visa',
    primaryColor: '#0072ce',
    gradient: 'linear-gradient(135deg, #003087 0%, #0056b3 60%, #00875a 100%)',
  },
  {
    key: 'citibank',
    name: 'Citibank Nigeria',
    short: 'Citibank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#003b70',
    gradient: 'linear-gradient(135deg, #002244 0%, #003b70 60%, #00172e 100%)',
  },
  {
    key: 'unity',
    name: 'Unity Bank Plc',
    short: 'Unity Bank',
    category: 'commercial',
    defaultScheme: 'verve',
    primaryColor: '#f37021',
    gradient: 'linear-gradient(135deg, #064e3b 0%, #047857 60%, #9a3412 100%)',
  },
  {
    key: 'globus',
    name: 'Globus Bank',
    short: 'Globus Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#7b1113',
    gradient: 'linear-gradient(135deg, #3f090a 0%, #7b1113 60%, #1c1917 100%)',
  },
  {
    key: 'premiumtrust',
    name: 'PremiumTrust Bank',
    short: 'PremiumTrust',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#001e3d',
    gradient: 'linear-gradient(135deg, #082f49 0%, #0369a1 60%, #082f49 100%)',
  },
  {
    key: 'titan',
    name: 'Titan Trust Bank',
    short: 'Titan Trust',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#bfa054',
    gradient: 'linear-gradient(135deg, #1c1917 0%, #292524 60%, #78350f 100%)',
  },
  {
    key: 'suntrust',
    name: 'SunTrust Bank',
    short: 'SunTrust',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#00a3e0',
    gradient: 'linear-gradient(135deg, #0369a1 0%, #0284c7 60%, #075985 100%)',
  },
  {
    key: 'parallex',
    name: 'Parallex Bank',
    short: 'Parallex Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#d62226',
    gradient: 'linear-gradient(135deg, #1c1917 0%, #292524 60%, #991b1b 100%)',
  },
  {
    key: 'signature',
    name: 'Signature Bank',
    short: 'Signature Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#1e293b',
    gradient: 'linear-gradient(135deg, #0f172a 0%, #1e293b 60%, #334155 100%)',
  },
  {
    key: 'optimus',
    name: 'Optimus Bank',
    short: 'Optimus Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#0284c7',
    gradient: 'linear-gradient(135deg, #075985 0%, #0284c7 60%, #0369a1 100%)',
  },
  {
    key: 'nova',
    name: 'Nova Commercial Bank',
    short: 'Nova Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#0284c7',
    gradient: 'linear-gradient(135deg, #0c4a6e 0%, #075985 60%, #0369a1 100%)',
  },

  // ── Digital Neobanks & Top FinTech MFBs ──
  {
    key: 'kuda',
    name: 'Kuda Microfinance Bank',
    short: 'Kuda Bank',
    category: 'digital',
    defaultScheme: 'verve',
    primaryColor: '#40196d',
    gradient: 'linear-gradient(140deg, #240a42 0%, #40196d 55%, #561d8f 100%)',
    isPopular: true,
  },
  {
    key: 'opay',
    name: 'OPay (PayCom MFB)',
    short: 'OPay',
    category: 'digital',
    defaultScheme: 'verve',
    primaryColor: '#00b875',
    gradient: 'linear-gradient(135deg, #022c22 0%, #065f46 50%, #059669 100%)',
    isPopular: true,
  },
  {
    key: 'moniepoint',
    name: 'Moniepoint Microfinance Bank',
    short: 'Moniepoint',
    category: 'digital',
    defaultScheme: 'mastercard',
    primaryColor: '#003399',
    gradient: 'linear-gradient(135deg, #021e42 0%, #003399 55%, #1d4ed8 100%)',
    isPopular: true,
  },
  {
    key: 'palmpay',
    name: 'PalmPay (PalmPay MFB)',
    short: 'PalmPay',
    category: 'digital',
    defaultScheme: 'verve',
    primaryColor: '#2a4bff',
    gradient: 'linear-gradient(135deg, #172554 0%, #1e40af 50%, #2563eb 100%)',
    isPopular: true,
  },
  {
    key: 'fairmoney',
    name: 'FairMoney MFB',
    short: 'FairMoney',
    category: 'digital',
    defaultScheme: 'verve',
    primaryColor: '#00c2cb',
    gradient: 'linear-gradient(135deg, #083344 0%, #0e7490 60%, #155e75 100%)',
  },
  {
    key: 'carbon',
    name: 'Carbon Microfinance Bank',
    short: 'Carbon',
    category: 'digital',
    defaultScheme: 'visa',
    primaryColor: '#1e293b',
    gradient: 'linear-gradient(135deg, #0f172a 0%, #1e293b 60%, #334155 100%)',
  },
  {
    key: 'vbank',
    name: 'VBank (VFD Microfinance Bank)',
    short: 'VBank (VFD)',
    category: 'digital',
    defaultScheme: 'mastercard',
    primaryColor: '#dc2626',
    gradient: 'linear-gradient(135deg, #450a0a 0%, #991b1b 60%, #dc2626 100%)',
  },
  {
    key: 'sparkle',
    name: 'Sparkle Microfinance Bank',
    short: 'Sparkle MFB',
    category: 'digital',
    defaultScheme: 'visa',
    primaryColor: '#10b981',
    gradient: 'linear-gradient(135deg, #064e3b 0%, #059669 60%, #10b981 100%)',
  },
  {
    key: 'gomoney',
    name: 'GoMoney (Sterling MFB)',
    short: 'GoMoney',
    category: 'digital',
    defaultScheme: 'mastercard',
    primaryColor: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #4c1d95 0%, #6d28d9 60%, #7c3aed 100%)',
  },
  {
    key: 'raven',
    name: 'Raven Bank (Raven Millionaire MFB)',
    short: 'Raven Bank',
    category: 'digital',
    defaultScheme: 'verve',
    primaryColor: '#0284c7',
    gradient: 'linear-gradient(135deg, #0369a1 0%, #0284c7 60%, #0ea5e9 100%)',
  },
  {
    key: 'dot',
    name: 'Dot MFB (Dot Bank)',
    short: 'Dot Bank',
    category: 'digital',
    defaultScheme: 'visa',
    primaryColor: '#e11d48',
    gradient: 'linear-gradient(135deg, #881337 0%, #be123c 60%, #e11d48 100%)',
  },
  {
    key: 'pocket',
    name: 'Pocket App (Piggyvest / Abeg)',
    short: 'Pocket App',
    category: 'digital',
    defaultScheme: 'mastercard',
    primaryColor: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #581c87 0%, #7e22ce 60%, #9333ea 100%)',
  },
  {
    key: 'mintyn',
    name: 'Mintyn Bank (Mint MFB)',
    short: 'Mintyn Bank',
    category: 'digital',
    defaultScheme: 'verve',
    primaryColor: '#0f766e',
    gradient: 'linear-gradient(135deg, #134e4a 0%, #0f766e 60%, #14b8a6 100%)',
  },
  {
    key: 'branch',
    name: 'Branch Microfinance Bank',
    short: 'Branch MFB',
    category: 'digital',
    defaultScheme: 'mastercard',
    primaryColor: '#2563eb',
    gradient: 'linear-gradient(135deg, #1e3a8a 0%, #1d4ed8 60%, #3b82f6 100%)',
  },
  {
    key: 'rubies',
    name: 'Rubies Bank (Rubies MFB)',
    short: 'Rubies Bank',
    category: 'digital',
    defaultScheme: 'mastercard',
    primaryColor: '#db2777',
    gradient: 'linear-gradient(135deg, #831843 0%, #be185d 60%, #db2777 100%)',
  },
  {
    key: 'nomba',
    name: 'Nomba (Kudi MFB)',
    short: 'Nomba',
    category: 'digital',
    defaultScheme: 'mastercard',
    primaryColor: '#ea580c',
    gradient: 'linear-gradient(135deg, #7c2d12 0%, #c2410c 60%, #ea580c 100%)',
  },
  {
    key: 'chipper',
    name: 'Chipper Cash',
    short: 'Chipper Cash',
    category: 'digital',
    defaultScheme: 'visa',
    primaryColor: '#6366f1',
    gradient: 'linear-gradient(135deg, #312e81 0%, #4338ca 60%, #6366f1 100%)',
  },

  // ── Non-Interest & Islamic Banks ──
  {
    key: 'jaiz',
    name: 'Jaiz Bank Plc',
    short: 'Jaiz Bank',
    category: 'commercial',
    defaultScheme: 'verve',
    primaryColor: '#007a3d',
    gradient: 'linear-gradient(135deg, #064e3b 0%, #047857 60%, #022c22 100%)',
  },
  {
    key: 'taj',
    name: 'TAJBank Ltd',
    short: 'TAJBank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#8a0026',
    gradient: 'linear-gradient(135deg, #4c0519 0%, #881337 60%, #1f2937 100%)',
  },
  {
    key: 'lotus',
    name: 'Lotus Bank Ltd',
    short: 'Lotus Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#3d1a54',
    gradient: 'linear-gradient(135deg, #2e1065 0%, #4c1d95 60%, #064e3b 100%)',
  },
  {
    key: 'alternative',
    name: 'The Alternative Bank',
    short: 'Alternative Bank',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#047857',
    gradient: 'linear-gradient(135deg, #064e3b 0%, #047857 60%, #0f766e 100%)',
  },

  // ── Merchant Banks ──
  {
    key: 'coronation',
    name: 'Coronation Merchant Bank',
    short: 'Coronation',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#d97706',
    gradient: 'linear-gradient(135deg, #78350f 0%, #b45309 60%, #451a03 100%)',
  },
  {
    key: 'fbnquest',
    name: 'FBNQuest Merchant Bank',
    short: 'FBNQuest',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#041e42',
    gradient: 'linear-gradient(135deg, #041e42 0%, #0c2340 60%, #b45309 100%)',
  },
  {
    key: 'rand',
    name: 'Rand Merchant Bank Nigeria',
    short: 'RMB Nigeria',
    category: 'commercial',
    defaultScheme: 'visa',
    primaryColor: '#0f766e',
    gradient: 'linear-gradient(135deg, #134e4a 0%, #0f766e 60%, #042f2e 100%)',
  },
  {
    key: 'greenwich',
    name: 'Greenwich Merchant Bank',
    short: 'Greenwich',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#15803d',
    gradient: 'linear-gradient(135deg, #14532d 0%, #15803d 60%, #052e16 100%)',
  },
  {
    key: 'fsdh',
    name: 'FSDH Merchant Bank',
    short: 'FSDH',
    category: 'commercial',
    defaultScheme: 'mastercard',
    primaryColor: '#1e3a8a',
    gradient: 'linear-gradient(135deg, #172554 0%, #1e3a8a 60%, #1e1b4b 100%)',
  },

  // ── Leading National & State Microfinance Banks ──
  {
    key: 'lapo',
    name: 'LAPO Microfinance Bank',
    short: 'LAPO MFB',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#eab308',
    gradient: 'linear-gradient(135deg, #713f12 0%, #a16207 60%, #ca8a04 100%)',
  },
  {
    key: 'accion',
    name: 'Accion Microfinance Bank',
    short: 'Accion MFB',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#0284c7',
    gradient: 'linear-gradient(135deg, #075985 0%, #0284c7 60%, #0369a1 100%)',
  },
  {
    key: 'baobab',
    name: 'Baobab Microfinance Bank',
    short: 'Baobab MFB',
    category: 'microfinance',
    defaultScheme: 'mastercard',
    primaryColor: '#d97706',
    gradient: 'linear-gradient(135deg, #78350f 0%, #b45309 60%, #d97706 100%)',
  },
  {
    key: 'abmfb',
    name: 'AB Microfinance Bank Nigeria',
    short: 'AB MFB',
    category: 'microfinance',
    defaultScheme: 'mastercard',
    primaryColor: '#dc2626',
    gradient: 'linear-gradient(135deg, #7f1d1d 0%, #b91c1c 60%, #dc2626 100%)',
  },
  {
    key: 'mutualtrust',
    name: 'Mutual Trust Microfinance Bank',
    short: 'Mutual Trust',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#0d9488',
    gradient: 'linear-gradient(135deg, #115e59 0%, #0f766e 60%, #0d9488 100%)',
  },
  {
    key: 'peace',
    name: 'Peace Microfinance Bank',
    short: 'Peace MFB',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#16a34a',
    gradient: 'linear-gradient(135deg, #166534 0%, #15803d 60%, #16a34a 100%)',
  },
  {
    key: 'alert',
    name: 'Alert Microfinance Bank',
    short: 'Alert MFB',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#f59e0b',
    gradient: 'linear-gradient(135deg, #78350f 0%, #d97706 60%, #f59e0b 100%)',
  },
  {
    key: 'renmoney',
    name: 'Renmoney Microfinance Bank',
    short: 'Renmoney',
    category: 'microfinance',
    defaultScheme: 'mastercard',
    primaryColor: '#ef4444',
    gradient: 'linear-gradient(135deg, #991b1b 0%, #dc2626 60%, #ef4444 100%)',
  },
  {
    key: 'hasal',
    name: 'HASAL Microfinance Bank',
    short: 'HASAL MFB',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#4338ca',
    gradient: 'linear-gradient(135deg, #312e81 0%, #3730a3 60%, #4338ca 100%)',
  },
  {
    key: 'infinity',
    name: 'Infinity Microfinance Bank',
    short: 'Infinity MFB',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#0284c7',
    gradient: 'linear-gradient(135deg, #0c4a6e 0%, #075985 60%, #0284c7 100%)',
  },
  {
    key: 'bosak',
    name: 'Bosak Microfinance Bank',
    short: 'Bosak MFB',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#059669',
    gradient: 'linear-gradient(135deg, #064e3b 0%, #047857 60%, #059669 100%)',
  },
  {
    key: 'mainstreet',
    name: 'Mainstreet Microfinance Bank',
    short: 'Mainstreet MFB',
    category: 'microfinance',
    defaultScheme: 'verve',
    primaryColor: '#1e3a8a',
    gradient: 'linear-gradient(135deg, #172554 0%, #1e3a8a 60%, #2563eb 100%)',
  },

  // ── Universal Other / Custom Bank ──
  {
    key: 'other',
    name: 'Other Licensed Bank or FinTech',
    short: 'Other Bank',
    category: 'other',
    defaultScheme: 'mastercard',
    primaryColor: '#1d4ed8',
    gradient: 'linear-gradient(135deg, #0a1738 0%, #132454 45%, #1e3a8a 100%)',
  },
];

export function findBank(keyOrName: string): BankMeta {
  if (!keyOrName) return ALL_NIGERIAN_BANKS[0]!;

  const query = keyOrName.toLowerCase().trim();
  const exact = ALL_NIGERIAN_BANKS.find(
    (b) => b.key === query || b.name.toLowerCase() === query || b.short.toLowerCase() === query
  );
  if (exact) return exact;

  const partial = ALL_NIGERIAN_BANKS.find(
    (b) =>
      b.key.includes(query) ||
      b.name.toLowerCase().includes(query) ||
      b.short.toLowerCase().includes(query)
  );

  return (
    partial ??
    ALL_NIGERIAN_BANKS.find((b) => b.key === 'other') ??
    ALL_NIGERIAN_BANKS[0]!
  );
}
